FROM nginx:latest


LABEL version="0.0.1"

EXPOSE 80

WORKDIR /usr/share/nginx/html
COPY webapp/index.html index.html
COPY webapp/style.css style.css

COPY webapp/media/1.jfif media/1.jfif
COPY webapp/media/4.jfif media/4.jfif
COPY webapp/media/ayush.jpg media/ayush.jpg 
COPY webapp/media/ayushishu.png media/ayushishu.png
COPY webapp/media/icon.png media/icon.png
CMD gunicorn --bind 0.0.0.0:$PORT wsgi 