apiVersion: apps/v1

kind: Deployment

metadata:

  name: who-is-ayush-website-de-deployment

  labels:

    app: who-is-ayush-website-dev

spec:

  replicas: 2

  selector:

    matchLabels:

      app: who-is-ayush-website-dev

  template:

    metadata:

      labels:

        app: who-is-ayush-website-dev

    spec:

      containers:

      - name: who-is-ayush-website-dev-con

        image: ayushishu/who-is-ayush-website-dev:v1

        ports:

        - containerPort: 80
